### ISSUE TITLE
Hardware: Review mechanical attachment method

### ISSUE THREAD

**Issue by andrempmattos** [spacelab-ufsc/battery-module-4c#4]
**Overview:**
It is necessary to review the mechanical attachment for a plastic/polymer cover/wrapper. Since there are 4 batteries and the terminals are closer, shortcuts or detachment could be a problem during the vibration tests patterns. Also, the wrapper presents assembly challenges during the integration, then a simpler method could ease these procedures and improve the overall feasibility. 

**Some ideas/recomendations/suggestions to be analysed:**

It could improve the wrapper attachment in the PCB since there are no loose pieces/bolts/washer:
![image](https://user-images.githubusercontent.com/25351149/85945768-31a27f80-b940-11ea-9eae-63918145d1fb.png)

Maybe the same method used in other electronic devices with the plastic borders attached even without bolts:

![image](https://user-images.githubusercontent.com/25351149/85946080-3405d900-b942-11ea-976f-95ec1976276d.png)

**Comment by YanAzer** [comment]
Some new images for inspiration:
![image](https://user-images.githubusercontent.com/40373964/107572589-39f7b400-6bcb-11eb-8809-1513792ea594.png)
![image](https://user-images.githubusercontent.com/40373964/107572637-4b40c080-6bcb-11eb-8714-75963dd6a7fb.png)
https://www.google.com/imgres?imgurl=x-raw-image:///6634c2ea12cae2710d74224933948a37fe1926551f1a21b6ea2360aa884c3e4f&imgrefurl=http://mstl.atl.calpoly.edu/~workshop/archive/2018/Spring/Day%25201/Session%25202/NathanEngland.pdf&tbnid=ceLKEurCNGZkVM&vet=1&docid=Pg2TiIZvuWyThM&w=666&h=435&source=sh/x/im
https://www.google.com/imgres?imgurl=http://www.imtsrl.it/_media/img/large/battery-pack-3-1024x682.jpg&imgrefurl=http://www.imtsrl.it/battery-pack.html&tbnid=6zWjY_rsfmTN3M&vet=1&docid=XPJP-t2zuxd0rM&w=1024&h=682&source=sh/x/im

**Comment by YanAzer** [comment]
@spacelab-ufsc/mechanical some new ideas for the new mechanical case @kiqsmg:

1) Add new mouting holes between the batteries, this will require them to be a bit more spaced.

![](https://cdn.discordapp.com/attachments/703306461467639900/836578463569805372/unknown.png)

2) Add a "tab" on the sides of the pcb to be enable placing the required mouting holes.

![](https://cdn.discordapp.com/attachments/703306461467639900/836602206186635294/bat4c-mod.png)

**Comment by kiqsmg** [comment]
Both options can work, but I still prefer the first one because it only requires to create more space between batteries and also helps to have a better fixation points (the closer the fixations are, the less vibration problems and bending possibility).
